### PR TITLE
Ensure a common sorted order

### LINKED ISSUE #24: Order of entries
Currently, files/directories are listed like in Github.
For example:
```
1
2
12
Z
a
```
I think it would be better to list them like that:
```
1
12
2
a
Z
```
What do you think?

It could be quickly done on server side (I can make a PR if wanted)
or a sort feature may be implemented in the frontend, but that may be overkill.

### PR DESCRIPTION
**Pull request by Maxime-J**
Can close #24

### CODE REVIEW

**Comment by mifi** [comment]
Thnaks for your PR. Why use `sensitivity: 'base'`. Isn't the default better?

**Comment by Maxime-J** [comment]
'base' sensitivity only takes into account base letter.
The default one is case/accents/marks sensitive.

Details can be checked here
https://reference.codeproject.com/Book/javascript/reference/global_objects/collator

**Comment by mifi** [comment]
I may be wrong but isn't it better to use `variant` when we are sorting so that case/accents/marks come in the right order also? If not I believe that these will have an unexpected order

**Comment by Maxime-J** [comment]
I had some concerns about the locale and so the rules being used when no locales are specified.
With base, we would have relied on the order node gave them for these special cases.

But as the system locale with undefined locales, you're right, it's surely better with the defaut sensitivity.

I update the commit :)

**Comment by mifi** [comment]
thanks!

**Pull request merged**
